apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: local
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.150.60
    path: "/var/nfsshare"
