apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-1
  labels:
   type: nfs
   storage: nfs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi